### ISSUE TITLE
"Photino.Blazor" - InputFile - OnChange callback is not "fired"

### ISSUE THREAD

**Issue by Smurf-IV** [tryphotino/photino.Samples#11]
Create the example `Photino.Blazor` project

add the following into Counter page:

![image](https://user-images.githubusercontent.com/2418812/111286329-fcf36700-8639-11eb-8486-03f199a026b4.png)
(This is simplfied - you can add `Console.WriteLine(obj.File);` if you think the callback is being optimised out !)

Set breakpoints as shown

- Run project
- click counter to confirm that the breakpoints are working
- Click "Choose File"
- Select any file and confirm that the filename is displayed next to the button

Expected:
- for the Callback to be fired
- And the breakpoint to be hit

Actual:
- Nothing.

**Comment by ottodobretsberger** [comment]
Thank you for reporting this issue. I will investigate the source of this problem with InputFile.

**Comment by ottodobretsberger** [comment]
For now, Blazor is no longer supported in Photino v2

**Comment by Mafyou** [comment]
Same bug here.
Wasm or Server or Auto: same.

The callback is never fired

**Comment by ottodobretsberger** [comment]
Since we did keep Blazor supported after all, we re-opened this issue to look into.

**Comment by MikeYeager** [comment]
We believe this is fixed along with https://github.com/tryphotino/photino.Blazor/issues/28
