### ISSUE TITLE
Multiwindow Not Supported on Windows

### ISSUE THREAD

**Issue by SamNChiet** [tryphotino/photino.Samples#13]
Pretty much what it says on the tin.
Right now I'm maintaining a crummy wrapper around photino that uses a Windows Forms web browser on Windows, which kinda... defeats the purpose of using photino on multiple platforms.

Is there a roadmap to native multiwindow support on Windows?

Thanks, all!

**Comment by MikeYeager** [comment]
@SamNChiet Yes there is! It's part of an upcoming release. We've cleared the technical hurdles, but need to decide just how much we can or should change the interface to accommodate it. Discussions are ongoing and we should have a new version finished in a few weeks.

**Comment by ottodobretsberger** [comment]
Fixed in Photino v2.
