### ISSUE TITLE
[new sample] something like drag and drop support possible?

### ISSUE THREAD

**Issue by congzhangzh** [tryphotino/photino.Samples#15]
Drag out maybe easy, how to do for drag in?

#reference
https://www.electronjs.org/docs/tutorial/native-file-drag-drop

**Comment by congzhangzh** [comment]
How to get drag files full path? This maybe depend on browser’s limitations ? Like mozFullPath?

a simple way is to use a textbox to accept drag, which will receive file path, Is this standard behavior?

**Comment by MikeYeager** [comment]
Drag and drop within the browser control is completely determined by the browser control. In our experience, drag and drop works exactly as it dies in a full browser. If you're having an issue, please let us know the specifics such as the platform you're running on and sample source code and we'll try to reproduce it.

**Comment by congzhangzh** [comment]
> Drag and drop within the browser control is completely determined by the browser control. In our experience, drag and drop works exactly as it dies in a full browser. If you're having an issue, please let us know the specifics such as the platform you're running on and sample source code and we'll try to reproduce it.

Ok, tks, I think it should work:)
