### ISSUE TITLE
HelloPhotino.NET cannot be opened on Mac

### ISSUE THREAD

**Issue by PaigeM89** [tryphotino/photino.Samples#18]
On Catalina 10.15.7, after creating a new `HelloPhotino.NET` application, `dotnet run` opens the application window (blank) and pops up a helpful error message:

```
The application can’t be opened.

-50
```

I have dotnet 5 installed (multiple versions), and I can recreate the issue from an empty project by adding Photino & trying to run from there.

**Comment by PaigeM89** [comment]
I get what I suspect is a _similar_ error in Ubuntu 21.04, a window that simply contains the message `The URL can't be shown`. I'll test these with an actual web URL next & see if this is isolated to using `.Load` on a file.

**Comment by drubie442** [comment]
Hey guys this is looking very cool.  However on Debian Buster I am getting the same error that PaigeM89 reports.  Works fine on Windows 10.  I have a pretty comprehensive .NET setup, I'm sure it's just a missing option on GTKWebKit to give it permission to load local files.  I don't know whether that is configurable directly through GTKWebKit or not as I'm unfamiliar with it.  It may be related to something like this: https://stackoverflow.com/questions/1834122/using-local-path-with-webview-webkit or some permission that needs to be enabled.

**Comment by philippjbauer** [comment]
We have found that the Photino.NET distribution v 2.0.11 might be corrupted. The projects in the debug branch are updated dependency to a recompiled version Photino.NET 2.0.12. We will do some testing on our side and release new versions of the samples soon. Feel free to test beforehand and give feedback if this solves the problem on your end as well.

**Comment by MikeYeager** [comment]
We posted a new version to NuGet yesterday that we believe fixes this issue for bouth Mac and Linux. Please give it a try and let us know if you still have problems. Thanks.

**Comment by jsoques** [comment]
I just re ran `dotnet new -i TryPhotino.VSCode.Project.Templates`
Then `dotnet new photinoapp -o MyPhotinoApp` 
Still errors. :(
![image](https://user-images.githubusercontent.com/12414216/134752386-5469df7f-bfc2-4fda-975e-8ac6cd56a6d8.png)
![image](https://user-images.githubusercontent.com/12414216/134752389-81dfd576-2916-46d9-abd9-290fa79bcf9c.png)

Running on:
System:    Kernel: 5.11.0-36-generic x86_64 bits: 64 Desktop: Xfce 4.16.0 Distro: Ubuntu 21.04 (Hirsute Hippo)

**Comment by philippjbauer** [comment]
A new version of the templates extensions based on the updated Photino.NET 2.0.13 version is available on Nuget: https://www.nuget.org/packages/TryPhotino.VSCode.Project.Templates/2.0.1

**Comment by jsoques** [comment]
Works, thanks.
