### ISSUE TITLE
WebRTC sample

### ISSUE THREAD

**Issue by Eagle3386** [tryphotino/photino.Samples#26]
Can you provide a sample for creation of a basic video chat app using WebRTC, please?

**Comment by ottodobretsberger** [comment]
We do not have capacity to work out extra samples like that. But if you want to contribute, we'd be happy to add that to our samples :)

**Comment by Eagle3386** [comment]
As I'm struggling to call WebRTC directly from C# (WinRTC is dead, MAUI won't support it for the foreseeable future & I refuse _any_ implementation using NodeJS), I thought of using Photino.
But since the contribution you're asking for requires _exactly_ what I asked for in the first place, we're in kinda merry-go-round, I guess.

So far, I managed to use WebRTC by calling Twilio's Video API via MAUI Blazor's `JSInterop` which I'm going to stay with until MAUI "non-Blazor" matured enough or MS comes up with yet another framework.

They taught us in school, software engineers would rationalize their own jobs one day - oh well, little did they know about Microsoft's framework "policy".. 🤣
