### ISSUE TITLE
Where exactly are these "mentioned" samples?

### ISSUE THREAD

**Issue by MollsAndHersh** [tryphotino/photino.Samples#28]
Advanced .NET with WebAPI, OS calls, PowerShell calls... I'm wanting to see the example that used Swagger and WebAPI locally that was shown in the demo video on YouTube.  Is this published somewhere?

**Comment by ottodobretsberger** [comment]
Unfortunately we had to drop the "Advanced .NET Sample" around native dialogues and powershell access, etc, due to limited resources. We still have the project and who knows, at some point we might revive it.
