### ISSUE TITLE
System.TypeInitializationException: 'The type initializer for 'PhotinoNET.PhotinoWindow' threw an exception.'

### ISSUE THREAD

**Issue by HenriApperloo** [tryphotino/photino.Samples#3]
I tried the sample, HelloPhotino.NET. What do I wrong ?

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'PhotinoNET.PhotinoWindow' threw an exception.
  Source=Photino.NET
  StackTrace:
   at PhotinoNET.PhotinoWindow..ctor(String title, Action`1 configure, Int32 width, Int32 height, Int32 left, Int32 top, Boolean fullscreen)
   at HelloPhotinoApp.Program.Main(String[] args) in D:\Download\photino.Samples-master\Photino.HelloPhotino.NET\Program.cs:line 55

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies: Kan opgegeven module niet vinden. (0x8007007E)

**Comment by MikeYeager** [comment]
It appears the WebView2 control is not installed. Please check that you're using the latest Photino.NET package 1.1.6. It should prompt you to install the control if it's not found. Otherwise you can install it manually from https://go.microsoft.com/fwlink/p/?LinkId=2124703
