### ISSUE TITLE
React version is long out of date.

### ISSUE THREAD

**Issue by raddevus** [tryphotino/photino.Samples#30]
The react version for the template project is very old & there are numerous warnings when building on that version.
Workaround: It is possible to replace the package.json & packages-lock.json files with files from a current (React 18.1.0).  
Please update the project template to use the newer version of React - package.json.
UPDATE
I have confirmed that I cannot get the basic template project to successfully npm run build
Many failures occur, many deprecated & even using npm audit fix --force doesn't seem to get me to a working build.
However, I am able to update the entire package.json to React 18.1.0 and npm run build works with no problems.

**Comment by raddevus** [comment]
I created a working fix to this problem (which will upgrade you to React 18.1.0).
All you have to do is copy the new files (package.json & package-lock.json) into your (old) template based project.
I have included readme instructions at the github I created with the files: 
[https://github.com/raddevus/PhotinoReactTemplateUpgrade](https://github.com/raddevus/PhotinoReactTemplateUpgrade)

I also included a make.bat which contains the long command which will npm build & dotnet build & run the project for you.

**Comment by ottodobretsberger** [comment]
Thank you, 
yes for this sample the version is outdated. 
If you'd like you could provide the updated json files as a PR and we will integrate them as soon as we can.

**Comment by MikeYeager** [comment]
Updated versions are now incorporated into the samples.
