### ISSUE TITLE
Cannot run ./Photino.Blazor.Sample from macOS

### ISSUE THREAD

**Issue by kasajian** [tryphotino/photino.Samples#34]
When I run from Terminal, it works:
./Photino.Blazor.Sample

But when I double-click on it from Finder, or type:
open ./Photino.Blazor.Sample

it doesn't work.  It says:
No application knows how to open ....

**Comment by MikeYeager** [comment]
To run through finder you have to package the application as a .app file. You can see an example here: https://github.com/philippjbauer/Photino.Native/tree/main/publish/PhotinoApp.app/Contents
