### ISSUE TITLE
Sagger sample .Net

### ISSUE THREAD

**Issue by franklupo** [tryphotino/photino.Samples#44]
Hi,
how to use swagger in .Net application?

best regards

**Comment by ramiabughazaleh** [comment]
Related: https://github.com/tryphotino/photino.Samples/issues/28

**Comment by MikeYeager** [comment]
@franklupo Swagger really has nothing to do with Photino. You can check out our repo of sample applications. The Server sample shows how to host ASP.NET WebAPI in Photino. You can turn on Swagger support as you would in any other ASP.NET application.
