### ISSUE TITLE
Add typescript version of the templates

### ISSUE THREAD

**Issue by annasajkh** [tryphotino/photino.Samples#47]
There is no typescript version of each frontend framework
i would appreciate if you could add it
thanks

**Comment by annasajkh** [comment]
though i can add it manually but i would like to have it ready

**Comment by MikeYeager** [comment]
@annasajkh Thank you for the suggestion. Unfortunately, we don't have the bandwidth to maintain an extensive samples library. The samples are intentionally basic to provide a clear and concise starting point for common configurations. They're set up with the defaults for each framework for demonstration purposes.
