### ISSUE TITLE
Add documentation to Blazor sample to match namespace in _Imports.razor file

### ISSUE THREAD

**Issue by philippjbauer** [tryphotino/photino.Samples#6]
See issue https://github.com/tryphotino/photino.NET/issues/24

We need to add a description to notify users to match the namespace of their project.

Maybe there's a way to automate this?

**Comment by MikeYeager** [comment]
Don’t the templates create the project with our namespace? They have to manually change it, right? Also, there are probably going to be more errors in the code. We changed how we hooked up an event handler from using += to calling a method. We changed NativgateToUrl() to Load(). I forget what else.

Cheers!
Mike

From: Philipp Bauer ***@***.***>
Sent: Friday, March 12, 2021 11:39 AM
To: tryphotino/photino.Samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tryphotino/photino.Samples] Add documentation to Blazor sample to match namespace in _Imports.razor file (#6)


See issue tryphotino/photino.NET#24<https://github.com/tryphotino/photino.NET/issues/24>

We need to add a description to notify users to match the namespace of their project.

Maybe there's a way to automate this?

**Comment by philippjbauer** [comment]
The current VS Extension templates on the VS Marketplace are valid for the latest release versions. VS is creating a different namespace than what the `_Imports.razor` file is `@using` though. By default VS adds a `1` to the namespace in the `Program.cs` and `Startup.cs` but doesn't touch the `@using` statements in kind.

**Comment by ottodobretsberger** [comment]
Blazor no longer supported in Photino v2
