### ISSUE TITLE
Is consider add blazor server  side demo?

### ISSUE THREAD

**Issue by kefengwei** [tryphotino/photino.Samples#7]
Is consider add blazor server  side demo?

**Comment by peerem** [comment]
This is quasi server-side blazor. There are two differences: it uses the index.html like in WebAssembly and you don't have to configure the app, only the services. It is as easy to configure as WebAssembly with the full features of the server-side Blazor (complete framework with multithreading).

**Comment by MikeYeager** [comment]
Thanks @peerem. That's exactly right. Photino.Blazor doesn't use WASM or a server. All C# code is run against the locally installed, full .NET 5 framework.
